### ISSUE TITLE
vlccomp32, vhicomp32 corrupt memory for small input buffers

### ISSUE THREAD

**Issue by pps83** [powturbo/TurboPFor#130]
when input buffer is less than 8 bytes these will corrupt memory. I think these start writing at tmp[-4]. If input buffer size is 0, then lz4 will be called with size_t(0-4).

Another issue, vsdec32 supposedly returns end of consumed input buffer. It returns sometimes 1 byte less than expected.

**Comment by powturbo** [comment]
A memcpy input to output buffer is used when the input size is <= 32.
Should work now.

**Comment by pps83** [comment]
I had it fixed a bit differently: https://github.com/pps83/TurboPFor/commit/7e7a864fa8adb1fc9cadd60f25423fbf778142cb
You missed changes to other two functions
